import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ThemeProvider } from "~/components/share/theme-provider";
import { TRPCReactProvider } from "~/trpc/react";
import { SidebarProvider } from "~/components/ui/sidebar";
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "~/components/ui/resizable";
import { cn } from "~/lib/utils";
import { ChatSection } from "~/components/share/chat-section";
import { Sidebar } from "~/components/share/sidebar";
import { SessionProvider } from "next-auth/react";

export const metadata: Metadata = {
  title: "Promptify",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function AuthenticatedLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={GeistSans.variable} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TRPCReactProvider>
            <SessionProvider>
              <SidebarProvider>
                <div className="h-screen w-full flex flex-col bg-background">
                  <div className="flex flex-1 overflow-hidden h-full">
                    <Sidebar />

                    <ResizablePanelGroup
                      direction="horizontal"
                      className={cn(
                        "flex-1 transition-all duration-300 ease-in-out"
                      )}
                    >
                      <ResizablePanel className='p-5' defaultSize={75} minSize={30}>
                        {children}
                      </ResizablePanel>

                      <ResizableHandle withHandle />

                      <ResizablePanel minSize={30}>
                        <ChatSection />
                      </ResizablePanel>
                    </ResizablePanelGroup>
                  </div>
                </div>
              </SidebarProvider>
            </SessionProvider>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}